version: '3.8'

services:

  php:
    container_name: php-fs
    image: filesnap:dev
    volumes:
      - ./docker_config/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11.7
    container_name: mariadb-fs
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  caddy:
    image: caddy:2-alpine
    container_name: caddy-fs
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    ports:
      - '8080:80'
    depends_on:
      - php

volumes:
  mariadb_data:

